#!/bin/bash
# 
# chkconfig: 016 97 10
# description: Add DNS entries to Route53
#
### BEGIN INIT INFO
# Default-Stop: 0 1 6
# config: 
# pidfile: /var/lock/subsys/dnsRoute53
### END INIT INFO

. /etc/init.d/functions

## Command definition ##
DATE=/bin/date
ECHO=/bin/echo
TOUCH=/bin/touch
RM='rm -f'
PUPPET='/usr/bin/puppet agent --test'
SLEEP=/bin/sleep

## File definition ##
LOCKFILE=/var/lock/subsys/dnsRoute53
PUPPET_LOCKFILE=/var/lock/subsys/puppet
LOG=/var/log/routeupdates.log
PUPPET_LOCK_FILE=/var/lib/puppet/state/agent_catalog_run.lock

rh_status() {
    if [ -f $LOCKFILE ]; then
    	$ECHO "Service running..."
        exit 0
    else
    	$ECHO "Service is stopped"
        exit 1
    fi
}

case "$1" in
    start)
        if [ ! -f $LOCKFILE ]; then
			$DATE >> $LOG
        	/usr/sbin/create-dns-route53 >> $LOG 2>&1
        	RET=$? 
        	if [ $RET -eq 0 ] || [ $RET -eq 255 ]; then
        		$TOUCH $LOCKFILE
        		$ECHO "Service started successfully"
        		exit 0
        	else
        		$ECHO "Unable to create dns records. Stopping service..."
        		exit 1
        	fi
        	
       	else
       		$ECHO "$LOCKFILE already exists"
       		exit 1
       	fi
        ;;
    stop)
    	if [ -f $LOCKFILE ]; then
    		$DATE >> $LOG
    		/usr/sbin/delete-dns-route53 >> $LOG 2>&1
    		RET=$?
    		if [ $RET -eq 0 ] || [ $RET -eq 255 ]; then
    		   	$RM $LOCKFILE
    		   	$ECHO "Service stopped successfully"
    		   	exit 0
    		else
    			$ECHO "Unable to delete dns records. Service not stopped"
        		exit 1
    		fi
        else
        	$ECHO "$LOCKFILE doesn't exist"
        	exit 1
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        rh_status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
 
exit 0